export const tags = {
    activity: 'activity',
    adjective: 'adjective',
    adverb: 'adverb',
    animal: 'animal',
    clothing: 'clothing',
    counter: 'counter',
    country: 'country',
    day: 'day',
    family: 'family',
    food: 'food',
    greeting: 'greeting',
    iAdjective: 'い adjective',
    irregularVerb: 'irregular verb',
    major: 'major',
    money: 'money',
    month: 'month',
    naAdjective: 'な adjective',
    noun: 'noun',
    number: 'number',
    occupation: 'occupation',
    pg35: 'pg 35',
    pg40: 'pg 40 - pg 41',
    pg60: 'pg 60',
    pg69: 'pg 69',
    pg83: 'pg 83',
    pg86: 'pg 86 - pg 87',
    pg104: 'pg 104 - pg 105',
    pg106: 'pg 106',
    pg130: 'pg 130 - pg 131',
    pg148: 'pg 148 - pg 149',
    person: 'person',
    phrase: 'phrase',
    place: 'place',
	preposition: 'preposition',
    ruVerb: 'ru-verb',
    size: 'size',
    thing: 'thing',
    time: 'time',
    uVerb: 'u-verb',
    verb: 'verb',
    vocab: 'vocab',
};
